### PR TITLE
EZP-24924: Moved form mapper from repo forms

### PR DESCRIPTION
**Pull request by bdunogier**
Part of the extraction story.

Moves the FormMapper from the repository-forms package to this one. Class location can be discussed.

### CODE REVIEW

**Comment by bdunogier** [comment]
Ping @lolautruche @andrerom.

**Comment by andrerom** [comment]
The locations is as good as anything, +1

**Comment by lolautruche** [comment]
+1

**Comment by lserwatka** [comment]
Closing as we won't do any further work on legacy ezpage.

**Pull request closed without merging**
