### PR TITLE
EZP-24924: Extract Page field type out of kernel into separate repository

### PR DESCRIPTION
**Pull request by pspanja**
This PR resolves https://jira.ez.no/browse/EZP-24924

### CODE REVIEW

**Comment by bdunogier** [comment]
I'm wondering if we should have "fieldtype" in the repository / namespace. After all, the FieldType is just one aspect of this. It happens that this contains a fieldtype, but also more than that.

**Comment by andrerom** [comment]
I guess "FieldType" can indeed be skipped from ns, both in the main one, and from "lib/MVC/Symfony/FieldType/Page/PageServiceFactory.php". "Symfony" can also be skipped.

Note that @pspanja is on vacation for the next few weeks, so unless we re assign this task we might have to accept the structure as is to have the change in place.

**Comment by bdunogier** [comment]
I'd really rather do it before we tag the first stable. It should not take that much time...

**Comment by emodric** [comment]
https://github.com/ezsystems/ezpublish-kernel/pull/1496 & https://github.com/ezsystems/ezpublish-kernel/pull/1510 modified some behaviour that touches the block rendering, so this will probably need updating to match.

**Comment by andrerom** [comment]
true

**Comment by bdunogier** [comment]
I'm thinking we should just merge this, and cleanup once it is in.

What do you think ?

**Comment by andrerom** [comment]
+1

**Pull request merged**
